### ISSUE TITLE
Config -> Params -> Social -> Email - not working properly

### ISSUE THREAD

**Issue by milosgarunovic** [Track3/hermit#30]
Hi, I love your theme, hovever I've found a small bug.

In config.yml I have:
```
params:
  social:
    - name: "email"
      url: "my@email.com"
```
what I see as link to that email is `localhost:1313/about/my@email.com` (I can only see social section in about page for now, since I don't have anything else). I have github and linkedin working fine with https://...
