### ISSUE TITLE
Clickable header links are hard to see in mobile

### ISSUE THREAD

**Issue by zemien** [Track3/hermit#42]
Loving the new clickable header links (#36) but they're near invisible on mobile:

![image](https://user-images.githubusercontent.com/8407032/51959333-aa39ae00-24b8-11e9-8625-d00ea5775e4f.png)

**Comment by Track3** [comment]
Take a look at GitHub, their clickable links are also half invisible:

![ss](https://user-images.githubusercontent.com/34504964/52043845-a884ee80-257b-11e9-893a-74b128302794.png)

I'm fine with this, because these links requires mouse hover, on mobile, these don't get used very often.

To avoid this, We can simply use css media queries to make it not float to the left on mobile, but that will create another line sometimes:

![ss2](https://user-images.githubusercontent.com/34504964/52050468-96ab4780-258b-11e9-8dd6-0e859c8f3605.png)

Here's the code:
```css
@media (max-width: 520px) {
  .content a.anchor {
    float: none;
    margin-left: 4px;
    padding: 0;
  }
```
