### ISSUE TITLE
how to use nested menu

### ISSUE THREAD

**Issue by peter-jerry-ye** [Track3/hermit#53]
Sorry to disturb again. I'm trying to make a nested menu. Normally it should work if I add parent to config.yaml
```
menu:
  main:
  - identifier: a
    url: a/
    weight: 20
  - identifier: b
    url: b/
    weight: 100
  - identifier: c
    parent: b
    url: b/c/
    weight: 100
```
But in the ```b``` it doesn't have ```c``` though I can access with ```localhost:1313/b/c```. So what's wrong?
