### ISSUE TITLE
Table of content has been truncated

### ISSUE THREAD

**Issue by lniwn** [Track3/hermit#87]
My toc content has been truncated.
Post's url: <https://oaoa.me/posts/2018/%E6%B5%81%E7%95%85%E7%9A%84python%E5%AD%A6%E4%B9%A0%E7%AC%94%E8%AE%B0/>
![image](https://user-images.githubusercontent.com/3256188/61989673-b5cff100-b065-11e9-8630-82506a524d5c.png)

**Comment by efugier** [comment]
Try adding the following css
```css
#toc {
  overflow-y: auto;
  word-wrap: break-word;
}
```
here https://github.com/Track3/hermit/blob/master/assets/scss/style.scss#L682

**Comment by lniwn** [comment]
@efugier thank you for your help. I have got a scollbar with a custom css file `static/css/scroll-toc.css`
```css
#toc {
    left: auto;
    right: 1%;
    top: 5%;
    /* background: #494f5c; */
    width: 20%;
    height: 90%;
    overflow-y: auto;
    overflow-x: hidden;
    margin-right: -20px;
    padding-right:12px;
  }
```
